#@ load("@ytt:data", "data")

apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: #@ data.values.cluster_name
spec:
  version: #@ data.values.version
  #! Custom image with repository-s3 and discovery-ec2 plugins installed on top of the official Elastic image.
  #! Github link: https://github.com/SymphonyOSF/ElasticsearchKubernetes/blob/master/Dockerfile.elastic
  image: #@ data.values.image
  nodeSets:
    - name: master
      count: #@ int(int(data.values.node_configuration.master.count))
      volumeClaimTemplates:
        - metadata:
            #!           Name must always be elasticsearch-data
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: #@ data.values.node_configuration.master.storage_size
            storageClassName: gp2
      config:
        node.master: true
        node.data: false
        node.ingest: false
        node.ml: false
        cluster.routing.allocation.awareness.attributes: zone
      podTemplate:
        metadata:
          labels:
            sym-node-type: #@ str(data.values.cluster_name) +"-master-node"
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: #@ data.values.cluster_name
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          nodeSelector:
            beta.kubernetes.io/instance-type: #@ data.values.node_configuration.master.node_instance_type
          containers:
            - name: elasticsearch
              imagePullPolicy: Always
              resources:
                requests:
                  memory: #@ str(data.values.node_configuration.master.resources_per_node.memory-1) + "Gi"
                  cpu: #@ str(data.values.node_configuration.master.resources_per_node.cpu-1)
                limits:
                  memory: #@ str(data.values.node_configuration.master.resources_per_node.memory) + "Gi"
                  cpu: #@ str(data.values.node_configuration.master.resources_per_node.cpu)
    #@ for availability_zone in data.values.node_configuration.data.availability_zones:
    - name: #@ "data-"+ str(availability_zone.zone_name)
      count: #@ int(int(availability_zone.count))
      volumeClaimTemplates:
        - metadata:
            #! Name must always be elasticsearch-data
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: #@ data.values.node_configuration.data.storage_size
            storageClassName: gp2
      config:
        node.master: false
        node.data: true
        node.ingest: false
        node.ml: false
        bootstrap.memory_lock: false
        node.attr.zone: #@ availability_zone.zone_name
        cluster.routing.allocation.awareness.attributes: zone
      podTemplate:
        metadata:
          labels:
            sym-node-type: #@ str(data.values.cluster_name) +"-data-node"
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: #@ data.values.cluster_name
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                    - key: failure-domain.beta.kubernetes.io/zone
                      operator: In
                      values:
                        - #@ availability_zone.zone_name
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          nodeSelector:
            beta.kubernetes.io/instance-type: #@ data.values.node_configuration.data.node_instance_type
          containers:
            - name: elasticsearch
              imagePullPolicy: Always
              #!specify resource limits and requests
              resources:
                requests:
                  memory: #@ str(data.values.node_configuration.data.resources_per_node.memory-1) + "Gi"
                  cpu: #@ str(data.values.node_configuration.data.resources_per_node.cpu-1)
                limits:
                  memory: #@ str(data.values.node_configuration.data.resources_per_node.memory) + "Gi"
                  cpu: #@ str(data.values.node_configuration.data.resources_per_node.cpu)
    #@ end
  http:
    service:
      metadata:
        annotations:
          #!Must be a string
          service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: #@ data.values.elb.elastic.extraSecurityGroupIds
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
#!         external-dns.alpha.kubernetes.io/hostname: sym-search-dev-elastic.devi.symphony.com
      spec:
        type: LoadBalancer
        selector:
          sym-node-type: #@ str(data.values.cluster_name) +"-data-node"
        loadBalancerSourceRanges: #@ data.values.elb.elastic.loadBalancerSourceRanges
    #@ if data.values.elb.elastic.tls.customCertificate:
    tls:
      certificate:
        secretName: #@ data.values.elb.elastic.tls.k8sSecretName
    #@ end
