#@ load("@ytt:data", "data")
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: #@ "kibana-" + data.values.cluster_name
spec:
  version: 7.4.2
  count: 1
  config:
    elasticsearch.ssl.verificationMode: none
  elasticsearchRef:
    name: #@ data.values.cluster_name
  podTemplate:
    metadata:
      labels:
        sym-node-type: #@ str(data.values.cluster_name) +"-kibana-node"
    spec:
      #! The name of the container must always be kibana
      containers:
        - name: kibana
          resources:
            requests:
              memory: 0.5G
              cpu: 1
            limits:
              memory: 2G
              cpu: 2
      nodeSelector:
        beta.kubernetes.io/instance-type: t3.small
  http:
    service:
      metadata:
        annotations:
          #! Must be a string
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
          service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: #@ data.values.elb.elastic.extraSecurityGroupIds
          #! external-dns.alpha.kubernetes.io/hostname: sym-search-dev-kibana.devi.symphony.com
      spec:
        type: LoadBalancer
        selector:
          sym-node-type: #@ str(data.values.cluster_name) +"-kibana-node"
        loadBalancerSourceRanges: #@ data.values.elb.kibana.loadBalancerSourceRanges
    #@ if data.values.elb.kibana.tls.customCertificate:
    tls:
      certificate:
        secretName: #@ data.values.elb.kibana.tls.k8sSecretName
    #@ end
