apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: symsearch
spec:
  version: 7.4.2
#  Custom image with repository-s3 and discovery-ec2 plugins installed on top of the official Elastic image.
  image: luisplazas/elastic:7.4.2
  nodeSets:
#    Dedicated master node(s)
    - name: master
      count: 1
      config:
        node.master: true
        node.data: false
        node.ingest: false
        node.ml: false
        cluster.remote.connect: false
#      podTemplate:
#        spec:
#          nodeSelector:
#            beta.kubernetes.io/instance-type: m4.large
    - name: default
      count: 2
      config:
        node.master: false
        node.data: true
        node.ingest: flase
        node.ml: false
      podTemplate:
        metadata:
          labels:
            # additional labels for pods
            foo: bar
        spec:
          initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                requests:
                  memory: 28Gi
                  cpu: 6
                limits:
                  memory: 32Gi
                  cpu: 8

      # request 10Gi of persistent data storage for pods in this topology element
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: standard

#    secureSettings:
#    - secretName: ref-to-secret
#    - secretName: another-ref-to-secret
#     # expose only a subset of the secret keys (optional)
#     entries:
#     - key: value1
#       path: newkey # project a key to a specific path (optional)
  http:
   service:
     spec:
       type: LoadBalancer
       loadBalancerSourceRanges:
         - 208.184.224.194/32
         - 64.79.115.2/32
     tls:
       selfSignedCertificate:
         disabled: true
         # add a list of SANs into the self-signed HTTP certificate
#         subjectAltNames:
#         - ip: 192.168.1.2
#         - dns: "*.amazonaws.com"
  #     certificate:
  #       # provide your own certificate
  #       secretName: my-cert
