apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: symsearch
spec:
  version: 7.4.2
#  Custom image with repository-s3 and discovery-ec2 plugins installed on top of the official Elastic image.
  image: luisplazas/elastic:7.4.2
  nodeSets:
    - name: masters
      count: 1
      config:
        node.master: true
        node.data: false
        node.ingest: false
        node.ml: false
      podTemplate:
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          nodeSelector:
            beta.kubernetes.io/instance-type: c5.xlarge
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                requests:
                  memory: 7G
                  cpu: 3
                limits:
                  memory: 8G
                  cpu: 4
    - name: default
      count: 1
      volumeClaimTemplates:
        - metadata:
#            Name must always be elasticsearch-data
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 75Gi
            storageClassName: gp2
      config:
        node.master: false
        node.data: true
        node.ingest: false
        node.ml: false
        bootstrap.memory_lock: true
      podTemplate:
        metadata:
          labels:
            sym-node-type: "data"
        spec:
          nodeSelector:
            beta.kubernetes.io/instance-type: c5.2xlarge
          initContainers:
          - name: memlock-soft
            securityContext:
              privileged: true
            command: ['sh', '-c', 'echo "elasticsearch soft memlock unlimited" >> /etc/security/limits.conf']
          - name: memlock-hard
            securityContext:
              privileged: true
            command: ['sh', '-c', 'echo "elasticsearch hard memlock unlimited" >> /etc/security/limits.conf']
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                requests:
                  memory: 14G
                  cpu: 6
                limits:
                  memory: 16G
                  cpu: 8

#    secureSettings:
#    - secretName: ref-to-secret
#    - secretName: another-ref-to-secret
#     # expose only a subset of the secret keys (optional)
#     entries:
#     - key: value1
#       path: newkey # project a key to a specific path (optional)
  http:
   service:
     metadata:
       annotations:
#         Must be a string
         service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
     spec:
       type: LoadBalancer
       selector:
         sym-node-type: "data"
       loadBalancerSourceRanges:
         - 208.184.224.194/32
         - 64.79.115.2/32
         - 35.239.150.121/32
         - 35.188.142.59/32
         - 35.225.119.41/32
         - 35.227.18.124/32
         - 35.227.87.44/32
         - 35.237.136.190/32
#     tls:
#       selfSignedCertificate:
#         disabled: true
         # add a list of SANs into the self-signed HTTP certificate
#         subjectAltNames:
#         - ip: 192.168.1.2
#         - dns: "*.amazonaws.com"
  #     certificate:
  #       # provide your own certificate
  #       secretName: my-cert
